.de Sh \" Subsection
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp \" Vertical space (when we can't use .PP)
.if t .sp .5v
.if n .sp
..
.de Ip \" List item
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.TH "VSH" 8 "2004-07-29" "PlanetLab specific Vserver shell" "vsh"

.SH NAME
vsh \- Safely trampoline's a slice user from global vserver context to
the correspondingly named local vserver context\&.

.SH "SYNOPSIS"
 
.PP
\fBvsh\fR [COMMAND] \fR
 
.TP
[COMMAND]
when specified, the command to run, otherwise vsh will just run the
user's shell as a login shell

.SH "SUMMARY"
 
.PP
vsh is used as the login shell for slice users in the global vserver's
/etc/passwd\&. It is invoked either by sshd when a slice user logs on
to a PlanetLab node or as root using the su command\&. When this
occurs, vsh switches vserver context and sets the uid/gid of the slice
user, as specified in the slice's vserver /etc/passwd\&.

.PP
vsh assumes that the same account (by name) used to ssh/su into the
vserver also exists in the vserver specific /etc/passwd file\&.  This
is the only reason that for now it is deemed to be PlanetLab
specific\&.
