#!/bin/env python

import vserver, sys, os, re, getopt

def usage():
    print """
Usage:

%s [OPTION]... [COMMAND] [ARGUMENT]...

Options:


Commands:
        set slice space
	        Set max disk limit for a slice

        get slice
                Get current disk limit for slice
""" % (sys.argv[0])

    sys.exit(1)
    
def get(argv):
    slicename = argv[0]
    vs = vserver.VServer(slicename)
    limit = vs.get_disklimit()
    return "%s %d limit" % (slicename,limit)

def set(argv):
    slicename = argv[0]
    vs = vserver.VServer(slicename)
    oldlimit = vs.get_disklimit()
    newlimit = int(argv[1])
    if newlimit >= oldlimit:
        vs.set_disklimit(newlimit)
    return None

def main():
    functions = {"get":get, "set":set}
    argv = sys.argv[1:]
    if len(argv):
            func = functions.get(argv[0],usage)
            result = func(argv[1:])
            if result <> None:
                print result
	    sys.exit(0)

    # no command given
    usage()


if __name__ == '__main__':
    main()
