#!/bin/bash
#
# useradd(8) wrapper for vservers
#
# Mark Huang <mlhuang@cs.princeton.edu>
# Copyright (C) 2004-2006 The Trustees of Princeton University
#
# $Id: vuseradd,v 1.26 2006/11/13 18:49:31 mlhuang Exp $
#

: ${UTIL_VSERVER_VARS:=/usr/lib/util-vserver/util-vserver-vars}
test -e "$UTIL_VSERVER_VARS" || {
    echo "Can not find util-vserver installation; aborting..."
    exit 1
}
. "$UTIL_VSERVER_VARS"

shopt -s nullglob

# Defaults
TYPE="default"

usage()
{
    TYPES=
    pushd "$__DEFAULT_VSERVERDIR/.vref" >/dev/null
    for ref in * ; do
	if [ -z "$TYPES" ] ; then
	    TYPES=$ref
	else
	    TYPES="$TYPES, $ref"
	fi
    done
    popd >/dev/null

    echo "Usage: vuseradd [OPTION]... [NAME]"
    echo "	-t	Reference image type ($TYPES)"
    exit 1
}

# Get options
while getopts "t:" opt ; do
    case $opt in
	t)
	    TYPE="$OPTARG"
	    ;;
	*)
	    usage
	    ;;
    esac
done
shift $(($OPTIND - 1))

# Get slice name
[ -z "$1" ] && usage
NAME=$1

# Add slices group to /etc/group if not already present
groupadd slices 2>/dev/null || :

# Add slice name to /etc/passwd
useradd -g slices -s /bin/vsh $NAME -p '*'

USERID=`id -u $NAME`
GROUPID=`id -g $NAME`
GROUPNAME=`id -gn $NAME`

# Create /etc/vservers configuration file
if [ ! -f $__CONFDIR/$NAME.conf ] ; then
    sed \
	-e "s/.*S_CONTEXT=.*/S_CONTEXT=$USERID/" \
	-e "s/.*ONBOOT=.*/ONBOOT=yes/" \
	< $__PKGLIBDIR/defaults/sample.conf \
	> $__CONFDIR/$NAME.conf
fi

if [ ! -d "$__DEFAULT_VSERVERDIR/$NAME" ] ; then
    # Check the cache
    if [ "$TYPE" = "default" ] ; then
	for i in "$__DEFAULT_VSERVERDIR/.vcache/"* ; do
	    [ -d "$i" ] && mv "$i" "$__DEFAULT_VSERVERDIR/$NAME" && break
	done
    fi

    # Build slice from reference image
    if [ ! -d "$__DEFAULT_VSERVERDIR/$NAME" ] ; then
	REF="$__DEFAULT_VSERVERDIR/.vref/$TYPE"

	# Build in temporary directory
	mkdir -p "$__DEFAULT_VSERVERDIR/.vtmp"
	TMP=$(mktemp -d "$__DEFAULT_VSERVERDIR/.vtmp/$NAME.XXXXXX")
	"$__PKGLIBDIR/vbuild" "$REF" "$TMP"
	RETVAL=$?

	# Move it to its permanent location when complete
	if [ $RETVAL -eq 0 ] ; then 
	    mv "$TMP" "$__DEFAULT_VSERVERDIR/$NAME"
	else
	    echo "Error $RETVAL building $__DEFAULT_VSERVERDIR/$NAME"
	    rm -rf "$TMP" $__CONFDIR/$NAME.conf $__PKGSTATEDIR/$NAME.ctx
	    userdel -r $NAME
	    exit $RETVAL
	fi
    fi
fi

if [ -d "$__DEFAULT_VSERVERDIR/$NAME" ] ; then
    # Fix permissions
    chmod 755 "$__DEFAULT_VSERVERDIR/$NAME"

    # Add user in vserver
    $_VSERVER_LEGACY $NAME suexec root sh -c \
	"groupadd -g $GROUPID $GROUPNAME ; useradd -u $USERID -g $GROUPID -p '' $NAME"

    # Add an unrestricted entry to /etc/sudoers file
    if [ -f "$__DEFAULT_VSERVERDIR/$NAME/etc/sudoers" ] && \
       ! grep -q "^$NAME" "$__DEFAULT_VSERVERDIR/$NAME/etc/sudoers" ; then
	echo "$NAME	ALL=(ALL)	ALL" >> "$__DEFAULT_VSERVERDIR/$NAME/etc/sudoers"
    fi
fi

exit 0
