#!/bin/bash
#
# useradd(8) wrapper for vservers
#
# Copyright (c) 2004  The Trustees of Princeton University (Trustees).
#
# $Id: vuseradd,v 1.23 2005/08/21 21:41:03 mlhuang Exp $
#

: ${UTIL_VSERVER_VARS:=/usr/lib/util-vserver/util-vserver-vars}
test -e "$UTIL_VSERVER_VARS" || {
    echo "Can not find util-vserver installation; aborting..."
    exit 1
}
. "$UTIL_VSERVER_VARS"

usage()
{
    echo "usage: $0 name"
    exit 1
}

[ -z "$1" ] && usage
[ "$1" == "--static" ] && { STATIC=yes; shift; }
NAME=$1

# add slices group if not already present
groupadd slices 2>/dev/null || :

# add user
[ -z "$STATIC" ] && useradd -g slices -s /bin/vsh $NAME

# openssh-server 3.8 and above refuse login for "locked" accounts
for file in /etc/passwd /etc/shadow ; do
    [ -f $file ] && sed -i -e "s/$NAME:\!\!:\(.*\)/$NAME:*:\1/" $file
done

USERID=`id -u $NAME`
GROUPID=`id -g $NAME`
GROUPNAME=`id -gn $NAME`

# create vserver configuration file
if [ ! -f $__CONFDIR/$NAME.conf ] ; then
    sed \
	-e "s/.*S_CONTEXT=.*/S_CONTEXT=$USERID/" \
	-e "s/.*ONBOOT=.*/ONBOOT=yes/" \
	< $__PKGLIBDIR/defaults/sample.conf \
	> $__CONFDIR/$NAME.conf
fi

if [ ! -d "$__DEFAULT_VSERVERDIR/$NAME" ] ; then
    # check the cache
    shopt -s nullglob
    for i in "$__DEFAULT_VSERVERDIR/.vcache/"* ; do
	[ -d "$i" ] && mv "$i" "$__DEFAULT_VSERVERDIR/$NAME" && break
    done
    # build vserver
    if [ ! -d "$__DEFAULT_VSERVERDIR/$NAME" ] ; then
	# build in temporary directory
	TMP=$(mktemp -d "$__DEFAULT_VSERVERDIR/.$NAME.XXXXXX")
	"$__PKGLIBDIR/vbuild" "$__DEFAULT_VSERVERDIR/vserver-reference" "$TMP"
	RETVAL=$?
	# move it to its permanent location when complete
	if [ $RETVAL -ne 0 ] ; then 
	    echo "Error $RETVAL building $__DEFAULT_VSERVERDIR/$NAME"
	    rm -rf "$TMP" $__CONFDIR/$NAME.conf $__PKGSTATEDIR/$NAME.ctx
	    userdel -r $NAME
	    exit $RETVAL
	else
	    # sanity check
	    vnewsize=$(du -s "$TMP" | awk "{ print \$1 }")
	    vrefsize=$(du -s "$__DEFAULT_VSERVERDIR/vserver-reference" | awk "{ print \$1 }")
	    if [ $vnewsize -lt $vrefsize ] ; then
		echo "WARNING: Unexpected for 'du -s $__DEFAULT_VSERVERDIR/$NAME'=$vnewsize to be less than 'du -s $__DEFAULT_VSERVERDIR/vserver-reference'=$vrefsize"
	    fi

	    mv "$TMP" "$__DEFAULT_VSERVERDIR/$NAME"
	fi
    fi
fi

if [ -d "$__DEFAULT_VSERVERDIR/$NAME" ] ; then
    # fix permissions
    chmod 755 "$__DEFAULT_VSERVERDIR/$NAME"

    # add user in vserver
    $_VSERVER_LEGACY $NAME suexec root sh -c \
	"groupadd -g $GROUPID $GROUPNAME ; useradd -u $USERID -g $GROUPID -p '' $NAME"

    # add an unrestricted entry to /etc/sudoers file
    if [ -f "$__DEFAULT_VSERVERDIR/$NAME/etc/sudoers" ] && \
       ! grep -q "^$NAME" "$__DEFAULT_VSERVERDIR/$NAME/etc/sudoers" ; then
	echo "$NAME	ALL=(ALL)	ALL" >> "$__DEFAULT_VSERVERDIR/$NAME/etc/sudoers"
    fi
fi

# turn resource management on for vserver $NAME
chkconfig resman && service resman start $NAME
# XXX - resman doesn't print a trailing newline
echo
