#!/bin/bash
#
# userdel(8) wrapper for vservers
#
# Copyright (c) 2004  The Trustees of Princeton University (Trustees).
#
# $Id: vuserdel,v 1.6 2004/11/23 14:47:35 mlhuang Exp $
#

: ${UTIL_VSERVER_VARS:=$(dirname $0)/util-vserver-vars}
test -e "$UTIL_VSERVER_VARS" || {
    echo "Can not find util-vserver installation; aborting..."
    exit 1
}
. "$UTIL_VSERVER_VARS"

usage()
{
    echo "usage: $0 name"
    exit 1
}

[ -z "$1" ] && usage
NAME=$1

# read config file to get context ID
. /etc/vservers/$NAME.conf
CTX=$S_CONTEXT

# don't bother stopping gracefully, just kill all the processes
$SBINDIR/chcontext --silent --secure --ctx $CTX $PKGLIBDIR/vserverkillall

# unmount any directories in vserver that are mount points
for d in `sed -ne "s%^[^ ]* \($VROOTDIR/$NAME/[^ ]*\) .*%\1%p" /proc/mounts`
do
        # use echo -e to turn escaped whitespace back into regular chars
        # be careful about embedded backquotes here (i think we're safe)
        dir=`echo -e "$d"`
        echo "unmounting $dir"
        umount -l "$dir"
done

# turn resource management off for vserver $NAME
service resman stop $NAME

# delete user
userdel -r $NAME

# remove vserver configuration file
rm -f /etc/vservers/$NAME.conf

# remove vserver profile
rm -f /var/run/vservers/$NAME.ctx

# destroy vserver
if [ -d $VROOTDIR/$NAME ] ; then
    TMP=$(mktemp -d "$VROOTDIR/.vtmp/$NAME.XXXXXX")
    mv "$VROOTDIR/$NAME" "$TMP"
    rm -rf "$TMP"
fi
