#!/bin/bash
#
# userdel(8) wrapper for vservers
#
# Copyright (c) 2004  The Trustees of Princeton University (Trustees).
#
# $Id: vuserdel,v 1.4 2004/10/20 21:45:43 mef Exp $
#

: ${UTIL_VSERVER_VARS:=$(dirname $0)/util-vserver-vars}
test -e "$UTIL_VSERVER_VARS" || {
    echo "Can not find util-vserver installation; aborting..."
    exit 1
}
. "$UTIL_VSERVER_VARS"

usage()
{
    echo "usage: $0 name"
    exit 1
}

[ -z "$1" ] && usage
NAME=$1

# stop vserver
vserver $NAME stop

# turn resource management off for vserver $NAME
service resman stop $NAME

# delete user
userdel -r $NAME

# remove vserver configuration file
rm -f /etc/vservers/$NAME.conf

# remove vserver profile
rm -f /var/run/vservers/$NAME.ctx

# destroy vserver
if [ -d $VROOTDIR/$NAME ] ; then
    TMP=$(mktemp -d "$VROOTDIR/.vtmp/$NAME.XXXXXX")
    mv "$VROOTDIR/$NAME" "$TMP"
    chattr -R -i "$TMP"
    rm -rf "$TMP"
fi
